### ISSUE TITLE
Panamax doesn't handle self-updates

### ISSUE THREAD

**Issue by k3d3** [k3d3/panamax#2]
Rustup self-updates don't work on panamax, because the files needed for this are not mirrored.

**Comment by panzerballett** [comment]
hi!

i just started using panamax and it works perfectly well! thanks a lot!

but the issue about self-updates of rustup... are there any plans to mirror the necessary files as well? or is there  tool that would do just that?

thanks anyway and best regards!

**Comment by k3d3** [comment]
So I would like to mirror these files, but I'm not sure what all needs to be grabbed from the crates.io mirrors, how to discover said files, etc.

I'll try to ask on the Rust discord to see if anyone else knows, unless someone from @rust-lang can chime in who knows the architecture of crates.io better than I do.

For the time being, you should be able to re-download and run the rustup-init, and it'll act the same (it'll update the existing rustup, rather than replacing anything).

**Comment by panzerballett** [comment]
thanks a lot for your reply!

the error message i get (i.e. the file `rustup` wants to access first is):

    $ rustup update
    ...
    info: downloading self-update
    error: could not download file from 'http://panamax.internal/rustup/archive/1.20.2/x86_64-unknown-linux-gnu/rustup-init' to '/home/rust_user/.cargo/rustup-init'

(where i changed my internal server back to your `http://panamax.internal/rustup/` to make it correspond to your example setting).

**Comment by k3d3** [comment]
Right, makes sense. Unfortunately I'm not sure how exactly to mirror the rustup/archive directory, as there's no listing.

**Comment by k3d3** [comment]
https://github.com/rust-lang/rustup/blob/245b5885febcfa3106f531bef87fea529bacada3/src/cli/self_update.rs#L1025 Source code reference to this URL, as a note to myself

**Comment by k3d3** [comment]
I've added code to create and update the archive directory whenever rustup is updated, so hopefully this won't be a problem anymore.
